name: embracethechaos
favicon: null
layout_spectrum: 0.4788883391302079
typography_spectrum: 0.8422005798202008
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5372380649205297
  lightness: 0.06502146576531231
  saturation: 0.21823836001567543
  rhythmicContrast: 0.7568754381500185
purpose: []
